### ISSUE TITLE
Possibility of merge with `libadwaita` package

### ISSUE THREAD

**Issue by jesusrp98** [gtk-flutter/adwaita#10]
I was wondering why there are two 'adwaita' packages: one for the theming and colors and another for ui and widgets.

Inside the new `libadwaita` library offered by the GNOME project both style and widgets are inside one library, so it would make sense two merge this package into `libadwaita`.

I'd like this issue to serve as a point of discussion for all of us :)

**Comment by prateekmedia** [comment]
Hmm, I think this originated from here gtk-flutter/libadwaita#12

**Comment by MalcolmMielle** [comment]
This package enables users to use the Adwaita theme without having to import/use Adwaita widgets. That way, if I build an app using a custom widget, the Adwatia theme will be automatically applied, but I don't need to pull the whole library of Adwaita widgets.

**Comment by jesusrp98** [comment]
OK I see what you're saying there. I saw that Canonical is doing that for their theme.

Personally, I think it doesn't make too much sense, because if you plan to create new custom adwaita widgets in your app, there's a pretty good chance that you're also going to use any of the widgets offered by `libadwaita`.

This is just my personal opinion, not saying that this should be fixed or anything, just a thought :)

**Comment by MalcolmMielle** [comment]
If someone wants to simply adapt their existing app to have an Adwaita look without using the Adwaita widget, they can for now simply use the theme like any other Flutter theme. This way, the Adwaita ecosystem is more modulable and the theme can also be used on other platforms (in case libadwaita end-up being linux only).

I'd say we follow the Canonical way of doing it, simply because I see no upside for change :).
